USE [master]
GO
/****** Object:  Database [FinancialCrmDb]    Script Date: 19.01.2025 02:04:33 ******/
CREATE DATABASE [FinancialCrmDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FinancialCrmDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FinancialCrmDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FinancialCrmDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FinancialCrmDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FinancialCrmDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FinancialCrmDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FinancialCrmDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FinancialCrmDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FinancialCrmDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FinancialCrmDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FinancialCrmDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FinancialCrmDb] SET  MULTI_USER 
GO
ALTER DATABASE [FinancialCrmDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FinancialCrmDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FinancialCrmDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FinancialCrmDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FinancialCrmDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FinancialCrmDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FinancialCrmDb] SET QUERY_STORE = OFF
GO
USE [FinancialCrmDb]
GO
/****** Object:  Table [dbo].[BankProcesses]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BankProcesses](
	[BankProcessId] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](250) NULL,
	[ProcessDate] [date] NULL,
	[ProcessType] [nvarchar](50) NULL,
	[Amount] [decimal](18, 2) NULL,
	[BankId] [int] NULL,
 CONSTRAINT [PK_BankProcesses] PRIMARY KEY CLUSTERED 
(
	[BankProcessId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Banks]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Banks](
	[BankId] [int] IDENTITY(1,1) NOT NULL,
	[BankAccountNumber] [nvarchar](50) NULL,
	[BankTitle] [nvarchar](50) NULL,
	[BankBalance] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Banks] PRIMARY KEY CLUSTERED 
(
	[BankId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bills]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bills](
	[BillId] [int] IDENTITY(1,1) NOT NULL,
	[BillTitle] [nvarchar](50) NULL,
	[BillAmount] [decimal](18, 2) NULL,
	[BillPeriod] [nvarchar](50) NULL,
 CONSTRAINT [PK_Bills] PRIMARY KEY CLUSTERED 
(
	[BillId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](50) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Spendings]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Spendings](
	[SpendingId] [int] IDENTITY(1,1) NOT NULL,
	[SpendingTitle] [nvarchar](250) NULL,
	[SpendingAmount] [decimal](18, 2) NULL,
	[SpendingDate] [date] NULL,
	[CategoryId] [int] NULL,
 CONSTRAINT [PK_Spendings] PRIMARY KEY CLUSTERED 
(
	[SpendingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19.01.2025 02:04:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BankProcesses]  WITH CHECK ADD  CONSTRAINT [FK_BankProcesses_Banks] FOREIGN KEY([BankId])
REFERENCES [dbo].[Banks] ([BankId])
GO
ALTER TABLE [dbo].[BankProcesses] CHECK CONSTRAINT [FK_BankProcesses_Banks]
GO
ALTER TABLE [dbo].[Spendings]  WITH CHECK ADD  CONSTRAINT [FK_Spendings_Categories] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([CategoryId])
GO
ALTER TABLE [dbo].[Spendings] CHECK CONSTRAINT [FK_Spendings_Categories]
GO
USE [master]
GO
ALTER DATABASE [FinancialCrmDb] SET  READ_WRITE 
GO
